PARSER_VERSION = "section_extractor_v1"
METRICS_ENGINE_VERSION = "text_metrics_v3"
SCORING_MODEL_VERSION_V1 = "deterministic_scoring_v1"
SCORING_MODEL_VERSION = "deterministic_scoring_v2"
SCORING_MODEL_VERSION_V2 = SCORING_MODEL_VERSION
DICTIONARY_VERSION = "built_in_dictionaries_v3"

__all__ = [
    "PARSER_VERSION",
    "METRICS_ENGINE_VERSION",
    "SCORING_MODEL_VERSION",
    "SCORING_MODEL_VERSION_V1",
    "SCORING_MODEL_VERSION_V2",
    "DICTIONARY_VERSION",
]
